name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
        REPO_NAME: ${{secrets.DOCKER_HUB_REPO_NAME}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Get date Tag
      id: date
      run: echo "::set-output name=date::$(date +%s)"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $REPO_NAME
      
    - name: Docker Push
      run: docker push $REPO_NAME
